server:
  port : 8083

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/registration
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass@word1
