server:
  port : 8084

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/registration
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass@word1
  application:
    name: userregistration-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

